### PR TITLE
Make it possible to build with Go 1.23.

### LINKED ISSUE #546: [Bug]: Build fails with Go 1.23 because of changed testing.testDeps
**What happened**:

build fails with 
````
# github.com/kudobuilder/kuttl/pkg/test/utils
  pkg/test/utils/testing.go:44:28: cannot use &testDeps{} (value of type *testDeps) as "testing".testDeps value in argument to testing.MainStart: *testDeps does not implement "testing".testDeps (missing method InitRuntimeCoverage)
````

**What you expected to happen**:

build to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1) Install Go 1.23 (rc1, rc2 or later)
2) build

**Anything else we need to know?**:

Related:
* found while building with https://github.com/Homebrew/homebrew-core/pull/175310
* similar issue: https://github.com/hofstadter-io/hof/issues/391

**Environment**:
- Kubernetes version (use `kubectl version`):
- KUTTL version (use `kubectl kuttl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by porridge**
**What this PR does / why we need it**:

Paraphrasing the function doc:

> `MainStart` is not subject to the Go 1 compatibility document. It may change signature from release to release.

And so it did. This PR mimics what was done in https://github.com/hofstadter-io/hof/pull/392

Fixes #546

This seems to work with both of:
```
[kuttl]$ GOTOOLCHAIN=go1.23rc2 go build ./...
[kuttl]$ GOTOOLCHAIN=go1.22 go build ./...
```

### CODE REVIEW

**Review by vladbologa — APPROVED** [review]
LGTM
